### ISSUE TITLE
CSS not rendering properly 

### ISSUE THREAD

**Issue by Jased-0001** [Trihat243/Phoenix-web-browser#1]
Some CSS works, such as align but others don't.

![Screenshot 2023-01-17 at 6 30 03 PM](https://user-images.githubusercontent.com/108029829/213034921-07801c67-f113-42c4-b41f-1c2cd8ee2b16.png)
![Screenshot 2023-01-17 at 6 28 27 PM](https://user-images.githubusercontent.com/108029829/213034749-08e7587d-c3f9-40c0-86b4-a8add787ed9f.png)

**Comment by Trihat243** [comment]
strange, the only reason that i say that is the fact the page even renders colors correctly, i tested the browser on my Linux system and i went to google.com, the background was blue and the font was broken. i don't really know how to fix the CSS thing but hopefully someone else does.

**Comment by Jased-0001** [comment]
> strange, the only reason that i say that is the fact the page even renders colors correctly, i tested the browser on my Linux system and i went to google.com, the background was blue and the font was broken. i don't really know how to fix the CSS thing but hopefully someone else does.

I think it has something to do with the line ``displayEditorPane.setContentType("text/html");``
Apple M1 Mac, 8gb ram running Ventura 13.1 btw

**Comment by Trihat243** [comment]
would that have to be changed to ("text/html/CSS") or something?

**Comment by Trihat243** [comment]
Ok, the issue should be fixed. i changed it to displayEditorPane.setContentType("text/html/css"); the code executed without issues, i also added compatibility for HTTPS web pages. and i changed the window size
